@baseUrl = http://localhost:8080


# @name alive

GET {{baseUrl}}/alive/

####


# @name create_course

POST {{baseUrl}}/course/create
Content-Type: application/json

{
  "name":"Vue",
  "category":"WEB"
}

####

# @name find_all_courses

PUT {{baseUrl}}/course/46e58a33-1127-4cd8-9022-6c954fd650f6
Content-Type: application/json

{
  "name":"JavaScript"
}

####