version: '3.8'

services:
  postgres_nlw:
    container_name: challenger01
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=challenger01